addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"        % "0.1.3")
addSbtPlugin("org.lyranthe.sbt"          % "partial-unification" % "1.1.0")
addSbtPlugin("com.typesafe"              % "sbt-mima-plugin"     % "0.2.0")
addSbtPlugin("com.47deg"                 % "sbt-org-policies"    % "0.11.0")
addSbtPlugin("com.47deg"                 % "sbt-microsites"      % "0.9.4")
addSbtPlugin("com.timushev.sbt"          % "sbt-updates"         % "0.4.0")
addSbtPlugin("org.scoverage"             % "sbt-scoverage"       % "1.6.0-M5")
