addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"        % "0.1.10")
addSbtPlugin("org.lyranthe.sbt"          % "partial-unification" % "1.1.2")
addSbtPlugin("com.typesafe"              % "sbt-mima-plugin"     % "0.2.0")
addSbtPlugin("com.47deg"                 % "sbt-org-policies"    % "0.12.0-M3")
addSbtPlugin("com.47deg"                 % "sbt-microsites"      % "1.1.0")
addSbtPlugin("com.timushev.sbt"          % "sbt-updates"         % "0.5.0")
addSbtPlugin("org.scoverage"             % "sbt-scoverage"       % "1.6.1")
