package protobuf

import org.specs2.specification.core.SpecStructure
import org.specs2.Specification

class ProtobufSpec extends Specification {
  override def is: SpecStructure = s2"""
  Protobuf Schema

  It should be possible to create a ProtoF TMessage from a BaseDescriptor.

  """
}

object ProtobufTestUtils {
  import com.google.protobuf.descriptor.FieldDescriptorProto.Label.{LABEL_OPTIONAL, LABEL_REPEATED}
  import com.google.protobuf.descriptor.FieldDescriptorProto.Type.{TYPE_INT64, TYPE_MESSAGE, TYPE_STRING}
  import com.google.protobuf.descriptor._
  import scalapb.UnknownFieldSet

  val sampleFileDescriptorProto = FileDescriptorProto(
    Some("1543948401599.proto"),
    Some("com.book"),
    Vector(),
    Vector(),
    Vector(),
    Vector(
      DescriptorProto(
        Some("Book"),
        Vector(
          FieldDescriptorProto(
            Some("isbn"),
            Some(1),
            Some(LABEL_OPTIONAL),
            Some(TYPE_INT64),
            None,
            None,
            None,
            None,
            Some("isbn"),
            None
          ),
          FieldDescriptorProto(
            Some("title"),
            Some(2),
            Some(LABEL_OPTIONAL),
            Some(TYPE_STRING),
            None,
            None,
            None,
            None,
            Some("title"),
            None
          ),
          FieldDescriptorProto(
            Some("author"),
            Some(3),
            Some(LABEL_OPTIONAL),
            Some(TYPE_STRING),
            None,
            None,
            None,
            None,
            Some("author"),
            None
          )
        ),
        Vector(),
        Vector(),
        Vector(),
        Vector(),
        Vector(),
        None,
        Vector(),
        Vector()
      ),
      DescriptorProto(
        Some("GetBookRequest"),
        Vector(
          FieldDescriptorProto(
            Some("isbn"),
            Some(1),
            Some(LABEL_OPTIONAL),
            Some(TYPE_INT64),
            None,
            None,
            None,
            None,
            Some("isbn"),
            None
          )
        ),
        Vector(),
        Vector(),
        Vector(),
        Vector(),
        Vector(),
        None,
        Vector(),
        Vector()
      ),
      DescriptorProto(
        Some("GetBookViaAuthor"),
        Vector(
          FieldDescriptorProto(
            Some("author"),
            Some(1),
            Some(LABEL_OPTIONAL),
            Some(TYPE_STRING),
            None,
            None,
            None,
            None,
            Some("author"),
            None
          )
        ),
        Vector(),
        Vector(),
        Vector(),
        Vector(),
        Vector(),
        None,
        Vector(),
        Vector()
      ),
      DescriptorProto(
        Some("BookStore"),
        Vector(
          FieldDescriptorProto(
            Some("name"),
            Some(1),
            Some(LABEL_OPTIONAL),
            Some(TYPE_STRING),
            None,
            None,
            None,
            None,
            Some("name"),
            None
          ),
          FieldDescriptorProto(
            Some("books"),
            Some(2),
            Some(LABEL_REPEATED),
            Some(TYPE_MESSAGE),
            Some(".com.book.BookStore.BooksEntry"),
          None,
          None,
          None,
          Some("books"),
          None
        )
      ),
      Vector(),
      Vector(
        DescriptorProto(
          Some("BooksEntry"),
          Vector(
            FieldDescriptorProto(
              Some("key"),
              Some(1),
              Some(LABEL_OPTIONAL),
              Some(TYPE_INT64),
              None,
              None,
              None,
              None,
              Some("key"),
              None
            ),
            FieldDescriptorProto(
              Some("value"),
              Some(2),
              Some(LABEL_OPTIONAL),
              Some(TYPE_STRING),
              None,
              None,
              None,
              None,
              Some("value"),
              None
            )
          ),
          Vector(),
          Vector(),
          Vector(),
          Vector(),
          Vector(),
          Some(MessageOptions(
            None,
            None,
            None,
            Some(true),
            Vector(),
            UnknownFieldSet(Map())
          )),
          Vector(),
          Vector()
        )
      ),
      Vector(),
      Vector(),
      Vector(),
      None,
      Vector(),
      Vector()
    )
  ),
  Vector(
    EnumDescriptorProto(
      Some("EnumSample"),
      Vector(
        EnumValueDescriptorProto(
          Some("UNKNOWN"),
          Some(0),
          None
        ),
        EnumValueDescriptorProto(
          Some("STARTED"),
          Some(1),
          None
        ),
        EnumValueDescriptorProto(
          Some("RUNNING"),
          Some(1),
          None)
      ),
      Some(
        EnumOptions(
          Some(true),
          None,
          Vector(),
          UnknownFieldSet(Map())
        )
      )
    )
  ),
  Vector(
    ServiceDescriptorProto(
      Some("BookService"),
      Vector(
        MethodDescriptorProto(
          Some("GetBook"),
          Some(".com.book.GetBookRequest"),
        Some(".com.book.Book"),
      Some(
        MethodOptions(
          None,
          None,
          Vector(),
          UnknownFieldSet(Map())
        )
      ),
      None,
      None
    ),
    MethodDescriptorProto(
      Some("GetBooksViaAuthor"),
      Some(".com.book.GetBookViaAuthor"),
    Some(".com.book.Book"),
  Some(
    MethodOptions(
      None,
      None,
      Vector(),
      UnknownFieldSet(Map())
    )
  ),
  None,
  Some(true)
  ),
  MethodDescriptorProto(
    Some("GetGreatestBook"),
    Some(".com.book.GetBookRequest"),
  Some(".com.book.Book"),
  Some(
    MethodOptions(
      None,
      None,
      Vector(),
      UnknownFieldSet(Map())
    )
  ),
  Some(true),
  None
  ),
  MethodDescriptorProto(
    Some("GetBooks"),
    Some(".com.book.GetBookRequest"),
  Some(".com.book.Book"),
  Some(
    MethodOptions(
      None,
      None,
      Vector(),
      UnknownFieldSet(Map())
    )
  ),
  Some(true),
  Some(true))
  ),
  None
  )
  ),
  Vector(),
  None,
  None,
  Some("proto3")
  )
}
